# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='go group name')),
            ],
            options={
                'verbose_name': '\u90ae\u4ef6\u7ec4',
                'verbose_name_plural': '\u90ae\u4ef6\u7ec4',
            },
        ),
    ]
