# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailgroup',
            name='name',
            field=models.CharField(max_length=64, verbose_name='go group name'),
        ),
    ]
