# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20180704_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailgroup',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mailgroup',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
