# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0002_auto_20180704_1553'),
        ('publish', '0003_auto_20180704_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'1', '\u65e0\u9700\u5ba1\u6279'), (b'2', '\u4e00\u7ea7\u5ba1\u6279'), (b'3', '\u4e8c\u7ea7\u5ba1\u6279')], default=b'1', max_length=32, verbose_name='\u5ba1\u6279\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u5ba1\u6279\u7ea7\u522b',
                'verbose_name_plural': '\u5ba1\u6279\u7ea7\u522b',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.gogroup')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u521d\u59cb\u5316',
                'verbose_name_plural': '\u9879\u76ee\u521d\u59cb\u5316',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xa5\xe6\x9c\x9f')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xa5\xe6\x9c\x9f')),
                ('start_time', models.TimeField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4\xe7\x82\xb9')),
                ('end_time', models.TimeField(verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4\xe7\x82\xb9')),
                ('approval_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.ApprovalLevel')),
                ('project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.ProjectInfo')),
            ],
            options={
                'verbose_name': '\u65f6\u95f4\u6bb5',
                'verbose_name_plural': '\u65f6\u95f4\u6bb5',
            },
        ),
        migrations.AlterField(
            model_name='mailgroup',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='mail_group',
            field=models.ManyToManyField(related_name='project_mail_group', to='publish.MailGroup', verbose_name='\u90ae\u4ef6\u7ec4'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='owner',
            field=models.ManyToManyField(related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
    ]
