# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20180705_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u8282\u65e5\u540d\u79f0')),
                ('start_day', models.DateField(verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'verbose_name': '\u8282\u5047\u65e5',
                'verbose_name_plural': '\u8282\u5047\u65e5',
            },
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_date',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_of_week',
            field=models.CharField(choices=[(b'1', '\u661f\u671f\u4e00'), (b'2', '\u661f\u671f\u4e8c'), (b'3', '\u661f\u671f\u4e09'), (b'4', '\u661f\u671f\u56db'), (b'5', '\u661f\u671f\u4e94'), (b'6', '\u661f\u671f\u516d'), (b'7', '\u661f\u671f\u65e5')], default=b'7', max_length=32, verbose_name='\u622a\u6b62'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_of_week',
            field=models.CharField(choices=[(b'1', '\u661f\u671f\u4e00'), (b'2', '\u661f\u671f\u4e8c'), (b'3', '\u661f\u671f\u4e09'), (b'4', '\u661f\u671f\u56db'), (b'5', '\u661f\u671f\u4e94'), (b'6', '\u661f\u671f\u516d'), (b'7', '\u661f\u671f\u65e5')], default=b'1', max_length=32, verbose_name='\u8d77\u59cb'),
        ),
    ]
