# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20180709_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='first_approver',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_first_level_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u4e00\u7ea7\u5ba1\u6279\u4eba'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='mail_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_mail_group', to='publish.MailGroup', verbose_name='\u90ae\u4ef6\u7ec4'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='second_approver',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_second_level_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u4e8c\u7ea7\u5ba1\u6279\u4eba'),
        ),
    ]
